### ISSUE TITLE
Add Clock Project Using Html, CSS, JS

### ISSUE THREAD

**Issue by GundaSudarrshan** [MakeContributions/ideahub#102]
Hey I Wanted to a Digital Clock Project which can be made With Technologies Used : Javascript, CSS, HTML 
and wanted to know whether this project is in Hactoberfest-22 or not 
I wanted to contribute my Ideas

**Comment by prafullpandey614** [comment]
I wanna Contribute to this task please assign it to me

**Comment by ming-tsai** [comment]
> I wanna Contribute to this task please assign it to me

I guess @GundaSudarrshan is working on it, you could open a new issue for different idea

**Comment by prafullpandey614** [comment]
ok

**Comment by GundaSudarrshan** [comment]
@ming-tsai is your repo in hacktoberfest , I request to add labels for better readability, contributing 
 I am working on clock

**Comment by MahendraBishnoi29** [comment]
@ming-tsai is this repo open for hacktoberfest 2022?

**Comment by ming-tsai** [comment]
> > > @ming-tsai is this repo open for hacktoberfest 2022?
> > 
> > Well... I'm sure, but I will be investigating it.
> 
> please let me know fast I've to make 4 PR before this month ends.⭐

I guess this repo is not inside of the hacktoberfest, due to we have already participate in last year.

For more details read the below link 

https://hacktoberfest.com/participation/#pr-mr-details
```
[ EXCLUDED ]

REPOS THAT GO AGAINST HACKTOBERFEST’S VALUES WILL BE EXCLUDED FROM QUALIFICATION AND PR/MRS MADE TO THOSE REPOS WON’T COUNT.

```

**Comment by GundaSudarrshan** [comment]
@ming-tsai  so you mean this repo is not in hacktoberfest ??

**Comment by ming-tsai** [comment]
> @ming-tsai  so you mean this repo is not in hacktoberfest ??

Yeah... I found that has a rule, if the repo is participated previously it won't count.
