### ISSUE TITLE
Modify README.md

### ISSUE THREAD

**Issue by GundaSudarrshan** [MakeContributions/ideahub#115]
There are some mistakes in the README.md file , 
There are two places where (Website with Intermediate )tag is mentioned
![image](https://user-images.githubusercontent.com/70209862/194288821-dfc055fa-c727-48e6-91e9-12ac629ec77a.png)
should correct it 
@ming-tsai can you assign it to me

**Comment by ming-tsai** [comment]
> @ming-tsai then can we modify that action manually
> 

Well... I guess if modify manually it will replace it when the bot run.
