### ISSUE TITLE
Potential changes need to project links

### ISSUE THREAD

**Issue by jodylecompte** [MakeContributions/ideahub#119]
Hello  👋

I was looking over the site making a list of some small accessibility issues that could be improved, and I noticed a strange behavior with projects. 

Some idea cards link to a /projects route, while others do not:
<img width="975" alt="Screenshot of Idea Cards" src="https://user-images.githubusercontent.com/113849729/194719919-c44bba45-f91d-4470-a2d0-d61ed52d8cfb.png">

But their navigation is currently broken, for example, if you click the link for "Clash of Space" then the browser location updates to the following link, but does not re-render a new page: 
https://ideashub.netlify.app/Projects/clash-of-space

If you navigate to the URL directly, ie [https://ideashub.netlify.app/Projects/clash-of-space](https://ideashub.netlify.app/Projects/clash-of-space) then the page is completely blank. When you click on the Projects link, the cards instead have a Github icon and a link to a specific Github repo. Is this the behavior that should be carried over to the main ideas page or is something else supposed to happen?

Happy to submit a PR, just want to make sure I understand the expected behavior

**Comment by ming-tsai** [comment]
Hi @jodylecompte,
I guess the problem is the project is making the search with case sensitive, so if you go to the page as this https://ideashub.netlify.app/Projects/clash-of-space it works.

If you want to open a pull request, let me know.
