### ISSUE TITLE
Front End for the project

### ISSUE THREAD

**Issue by ming-tsai** [MakeContributions/ideahub#14]
Hi team,
I thinking creat a front-end for this project, like this one [What to code?](https://what-to-code.com/)

**Comment by UG-SEP** [comment]
I like it but sorry I have no experience in front-end

**Comment by ming-tsai** [comment]
I have had create [the website](https://ideashub.netlify.app/Ideas)

**Comment by HimanshuVaghelaa** [comment]
@ming-tsai Have any design in mind?
I can give it a shot, If you want to..

**Comment by HimanshuVaghelaa** [comment]
@ming-tsai  We can create cards to show different ideas, the card will display only title and tags,
And when the user will click on any card, We'll show the modal with detailed information of that particular card

**Comment by ming-tsai** [comment]
Well, I'm thinking that the card has overview of the website, and the repo that doesn't have website will have their icon

**Comment by UG-SEP** [comment]
add a suggest an idea add your project on the top right-hand side so people can click and navigate to this repo where they can suggest or add ideas/projects

**Comment by ming-tsai** [comment]
> add a suggest an idea add your project on the top right-hand side so people can click and navigate to this repo where they can suggest or add ideas/projects

Ok, thanks your suggestion

**Comment by pawitrawarda** [comment]
hi @ming-tsai are you still develop the frontend page? i can helps if you want to

**Comment by ming-tsai** [comment]
> hi @ming-tsai are you still develop the frontend page? i can helps if you want to

Ok @pawitrawarda, I will wait for your pull request

**Comment by Monsieur-Nico** [comment]
I would have helped but I have no experience with Vue. Most of my experience is with React but I can do some research on Vue and come back to help.

Let me know if I can somehow help with CSS or back-end

**Comment by ming-tsai** [comment]
Okis, @Monsieur-Nico I will wait for you pull request

**Comment by Monsieur-Nico** [comment]
> Okis, @Monsieur-Nico I will wait for you pull request

Is there a specific branch you want me to work on? or should I be cloning main branch?

**Comment by ming-tsai** [comment]
> > Okis, @Monsieur-Nico I will wait for you pull request
> 
> Is there a specific branch you want me to work on? or should I be cloning main branch?

You could cloning the main branch.

**Comment by ithiel883** [comment]
Hello, how can i contribute to this issue?

**Comment by ithiel883** [comment]
i keep getting gyp issues while trying to do an npm install of the project

**Comment by ming-tsai** [comment]
> i keep getting gyp issues while trying to do an npm install of the project

Hi @ithiel883,
Wich error is appearing when you're running the `npm install`, could you send me the screenshot or the logs?

**Comment by Basiru101** [comment]
Hi I'm new here and i will to contribute the projects as a programmer

**Comment by Basiru101** [comment]
Hi I'm a new member and will like to contribute to projects

**Comment by ithiel883** [comment]
> > i keep getting gyp issues while trying to do an npm install of the project
> 
> Hi @ithiel883, Wich error is appearing when you're running the `npm install`, could you send me the screenshot or the logs?

this is the error i get when trying to do an npm install, is it a python error?


npm ERR! code 1
npm ERR! path C:\Users\Admin\Documents\GitHub\ideahub\node_modules\deasync   
npm ERR! command failed
npm ERR! command C:\Windows\system32\cmd.exe /d /s /c node ./build.js        
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@9.0.0
npm ERR! gyp info using node@16.13.2 | win32 | x64
npm ERR! gyp info find Python using Python version 3.10.2 found at "C:\Users\Admin\AppData\Local\Programs\Python\Python310\python.exe"
npm ERR! gyp ERR! find VS
npm ERR! gyp ERR! find VS msvs_version not set from command line or npm config
npm ERR! gyp ERR! find VS VCINSTALLDIR not set, not running in VS Command Prompt
npm ERR! gyp ERR! find VS could not use PowerShell to find Visual Studio 2017 or newer, try re-running with '--loglevel silly' for more details
npm ERR! gyp ERR! find VS looking for Visual Studio 2015
npm ERR! gyp ERR! find VS - not found
npm ERR! gyp ERR! find VS not looking for VS2013 as it is only supported up to Node.js 8
npm ERR! gyp ERR! find VS
npm ERR! gyp ERR! find VS **************************************************************
npm ERR! gyp ERR! find VS You need to install the latest version of Visual Studio
npm ERR! gyp ERR! find VS including the "Desktop development with C++" workload.
npm ERR! gyp ERR! find VS For more information consult the documentation at: 
npm ERR! gyp ERR! find VS https://github.com/nodejs/node-gyp#on-windows      
npm ERR! gyp ERR! find VS **************************************************************
npm ERR! gyp ERR! find VS
npm ERR! gyp ERR! configure error
npm ERR! gyp ERR! stack Error: Could not find any Visual Studio installation 
to use
npm ERR! gyp ERR! stack     at VisualStudioFinder.fail (C:\Users\Admin\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:122:47)
npm ERR! gyp ERR! stack     at C:\Users\Admin\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:75:16
npm ERR! gyp ERR! stack     at VisualStudioFinder.findVisualStudio2013 (C:\Users\Admin\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:363:14)
npm ERR! gyp ERR! stack     at C:\Users\Admin\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:71:14
npm ERR! gyp ERR! stack     at C:\Users\Admin\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:384:16
npm ERR! gyp ERR! stack     at C:\Users\Admin\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\util.js:54:7
npm ERR! gyp ERR! stack     at C:\Users\Admin\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\util.js:33:16
npm ERR! gyp ERR! stack     at ChildProcess.exithandler (node:child_process:404:5)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:390:28)        
npm ERR! gyp ERR! stack     at maybeClose (node:internal/child_process:1064:16)
npm ERR! gyp ERR! System Windows_NT 10.0.19044
npm ERR! gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Admin\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
npm ERR! gyp ERR! cwd C:\Users\Admin\Documents\GitHub\ideahub\node_modules\deasync
npm ERR! gyp ERR! node -v v16.13.2
npm ERR! gyp ERR! node-gyp -v v9.0.0
npm ERR! gyp ERR! not ok
npm ERR! Build failed

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Admin\AppData\Local\npm-cache\_logs\2022-03-13T07_30_52_365Z-debug-0.log

**Comment by ming-tsai** [comment]
@ithiel883, could you try to resolve your problem go to the url?
<img width="645" alt="image" src="https://user-images.githubusercontent.com/37890026/158279713-37b4da09-d3ab-4f60-a4fa-d2f883d74f41.png">

**Comment by faiqali1** [comment]
Hi,

I noticed that the project still needs a front-end, and the issue is still open.

I would suggest going with Front-end Framework like [Next.js](https://nextjs.org/) or [SvelteKit](https://kit.svelte.dev/).

And I propose we use a Front-end Library like [TailwindCSS](https://tailwindcss.com/) or Bootstarp(https://getbootstrap.com/) to expedite the process.
