### ISSUE TITLE
Miss Typed in Contributing.md

### ISSUE THREAD

**Issue by UG-SEP** [MakeContributions/ideahub#9]
Hey,
@ming-tsai 
You have mistyped in contributing.md 
![idea](https://user-images.githubusercontent.com/75884061/114914388-d8a8c700-9e3f-11eb-9325-d3fbef6d4c9c.jpg)
cd ideahub

**Comment by ming-tsai** [comment]
Well that was a image from DSA project, if you want you could open a pull request then update the image

**Comment by UG-SEP** [comment]
issue resolved by @cyberwizard1001
